### ISSUE TITLE
map size, tile size

### ISSUE THREAD

**Issue by valteu** [hpi-swa-teaching/GameMecha#129]
Als **Nutzer** möchte ich die Größe des TileMap/Tiles dynamisch ändern können, damit ich bei Bedarf die Karte vergrößern kann.

> **NOTE**: Wenn die "tile size" verändert wird, muss der gesamte Editor-Zustand zurückgesetzt werden!

**Comment by ivozilkenat** [comment]
Es stellt sich die Frage, ob man zulässt, dass man durch die Verkleinerung Tiles entfernt - mit Vorwarnung - oder das einfach verbietet.
