### ISSUE TITLE
Profiling Tool for Keyboard Layout

### ISSUE THREAD

**Issue by tomschw** [hpi-swa-teaching/GameMecha#16]
![profilingtoolkeyboard-1](https://user-images.githubusercontent.com/18556787/27540421-6de8eb36-5a80-11e7-8055-a941e0290a13.png)
[ProfilingToolKeyboard.pdf](https://github.com/HPI-SWA-Teaching/SWT17-Project-13/files/1102116/ProfilingToolKeyboard.pdf)

**Comment by TMUKingston** [comment]
wir hatten uns schon gedanken gemacht:

```
|keyboard|
keyboard := GMKeyboard new.

keyboard
	registerAction: #walkForward
	toKey: #w
	hint: 'Walk forward'.

keyboard loadCalibrationIfExisting.

keyboard letUserRecalibrate.

(keyboard isActionKeyDown #walkForward)
	ifTrue: [self trolol].
```
