### ISSUE TITLE
Github resource loading (GitHub utility / complete folders)

### ISSUE THREAD

**Issue by ErikBrendel** [hpi-swa-teaching/GameMecha#25]
![2017-07-04 10 48 24](https://user-images.githubusercontent.com/11018565/27822629-95324a80-60a6-11e7-849e-4d58c74badc1.jpg)

**Comment by jakobbraun** [comment]
https://developer.github.com/v3/repos/contents/
https://api.github.com/repos/HPI-SWA-Teaching/SWT17-Project-13/contents/?ref=master

**Comment by jakobbraun** [comment]
ok. I just noticed there is even more work to be done:
* subfolders, recursive tree
* fassade is not good. We need something better!
