### ISSUE TITLE
Write Style guide

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#30]
## Story

As a dev i want to have a consistent style in my source code. Because of that i want a style guide

## Description

1. Why: It makes me look professional and i dont have to remember the style
2. What: Write style guide in Wiki (oriented at morphic)
3. Done: Style guide handles all the cases

**Comment by Tobias314** [comment]
We wrote an initial styleguide which can be found on the wiki. If you find important cases not covered by the styleguide please extend the styleguide and inform all the other team members.

**Comment by ben243871694** [comment]
time: 2
