### ISSUE TITLE
add simple collision [7]

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#32]
## Story

As a swa student I want to make my morphs that i used in my game collidable with each other

## Description

1. Why: collision is a big part of many games in SWA. Creating Functions that handle this might make the development of more complex games possibel
2. What: 
- [x] morph can test whether it collides with another morph (and which one)
- [x] morph can request a collection containing all morphs he is colliding with
- [x] tests are written which ensure that collision doesnt break

**Comment by oberam-eng** [comment]
moved to legacy.

**Comment by ben243871694** [comment]
estimate: 7

**Comment by Tobias314** [comment]
What is the difference between checkbox 1 and checkbox 2? We get a Collection of all morphs we are colliding with, this includes the fact whether we are colliding with a morph (list is not empty) or not (list ist empty).

**Comment by ekrebs5** [comment]
accepted
