### ISSUE TITLE
add optional gravitation to morphs [2]

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#33]
## Story

As a swa student I want to make my morphs be affected by gravity

## Description

1. Why: Having gravity in games is essential for many plattform-based games
2. What: 
- [ ] Morphs position is changed over time
- [ ] Rate of change, update and direction can change
- [ ] Handling for out of bounds situations

**Comment by oberam-eng** [comment]
moved to legacy.

**Comment by ben243871694** [comment]
estimation: 2

**Comment by ben243871694** [comment]
abandoned. not in scope, users should take care of it themselves
