### ISSUE TITLE
add collision for circle morphs [2]

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#34]
## Story

As a swa student i want to be able to have better collisions with circular morphs that does not depent on their axis aligning bounding box

## Description

1. Why: Circles that collide with their axis aligning bounding box can create weird artifacts(colliding when they shoudlnt)
2. What: 
- [x] add specific collision for circular morphs

**Comment by oberam-eng** [comment]
moved to legacy.

**Comment by ben243871694** [comment]
estimation: 2

**Comment by ekrebs5** [comment]
accepted
