### ISSUE TITLE
add pixel based collision [5]

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#35]
## Story

as a specific swa student I want to have pixel based collision to handle all kinds of different morphs

## Description

1. Why: pixel based collision provides a more accurate collision behavior
2. What:
- [ ] add optional pixel based collision for morphs

**Comment by oberam-eng** [comment]
moved to legacy.

**Comment by ben243871694** [comment]
estimation: 5

**Comment by ben243871694** [comment]
abandoned. complicated, performance issues, does not add much value
