### ISSUE TITLE
store image resources (like sprites) in methods  [1]

### ISSUE THREAD

**Issue by ben243871694** [hpi-swa-teaching/GameMecha#39]
As a SWA student I want to be able to sync my resources using monticello, hence they have to be stored in the image.

Acceptance:
- [x] resources in our own imageloader and soundloader are stored in this format
- [x] resources can be loaded, encoded and synced

**Comment by NiklasKoehnecke** [comment]
decoding onto disk is not necessary once you have it in the methods. If wanted we can add it, but we see it as dead code

**Comment by NiklasKoehnecke** [comment]
time needed: 1

**Comment by ekrebs5** [comment]
accepted
