### ISSUE TITLE
add Music Player [1]

### ISSUE THREAD

**Issue by arthurz0** [hpi-swa-teaching/GameMecha#40]
## Story
As a student I want to have background music playing in a loop until I tell it to stop.

##Description
1. Why: Having looping sounds you can tell to stop is important for many games.
2. What:
- [x] play a looped sound loaded by the sound manager
- [x] implement a method to stop the music
- [x] create acceptance test documenting how to use the music player

**Comment by ekrebs5** [comment]
accepted
