### ISSUE TITLE
Moving camera

### ISSUE THREAD

**Issue by Tobias314** [hpi-swa-teaching/GameMecha#42]
## Story

As a swa student, I want to be able to move my 2d camera so that I can position submorphs in something like a camera morph and the control where the  "camera" looks at and going left, right, up, down. This is useful for easily building for example sidescroller games like Super Mario where the camera moves along the world.
## Description

1. Why: Such common behavior should be provided by a special morph.
2. What: 
- [ ] Add a specific morph in which you can place Submorphs with a fixed "global position". These "camera morph" should also provide a function to change the field of view, which then moves submorphs accordingly.

**Comment by ben243871694** [comment]
abandoned. not in our scope, users should take care of it themselves
