### ISSUE TITLE
Key Bug [3]

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#43]
On Linux the key acceptance test (and collision acceptance) does currently not work

**Comment by ben243871694** [comment]
somehow fixed, works on travis. eva should try again

**Comment by ekrebs5** [comment]
problem persists (but the test is also green locally for me now)
investigating if it's a local problem for me or if other unix users also have this

**Comment by ekrebs5** [comment]
also occurs for other unix users, needs investigation

**Comment by NiklasKoehnecke** [comment]
time needed: 0.2 this iteration, probably 6+ overall

**Comment by ekrebs5** [comment]
accepted
