### ISSUE TITLE
Travis file loading [1]

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#44]
resources are written to fs from methods
- [x] store GIF
- [x] store PNG
- [x] store WAV
- [x] store AIFF
- [ ] working on travis

**Comment by NiklasKoehnecke** [comment]
Done. Effort : 5+ hours solo, so 2-3 hours pair

**Comment by NiklasKoehnecke** [comment]
seems to only work on 5.1
