### ISSUE TITLE
Collision Acceptance Test (visual) [1]

### ISSUE THREAD

**Issue by ben243871694** [hpi-swa-teaching/GameMecha#51]
## Story

As a user/developer I want to specify how the multiple different collisions should look and work like. Therefore i want an acceptance test which lets me communicate this to the developers.
Acceptance test should not include code.

## Description

**Why:**  
(What value does it have? For whom?)  
- customer can easily express his ideas, no need of coding skills
- developers can automatically test several testcases the customer stated
**What:**
 - [x] prototype (already implemented)
 - [x] separate tests so you can spot whats wrong (not all in one test)
 - [x] add pheno dependency to git / travis?
 - [x] sync automatically generated tests on git, currently only stored locally

**Comment by NiklasKoehnecke** [comment]
there appears to be no easy way to store morphs, making this a lot more difficult

**Comment by ben243871694** [comment]
todo: store position, extent, rotation instead of morphs. Then we can sync tests via git

**Comment by ekrebs5** [comment]
accepted

**Comment by ben243871694** [comment]
all of it took 4-5 hours
