### ISSUE TITLE
example game implementation [2]

### ISSUE THREAD

**Issue by ben243871694** [hpi-swa-teaching/GameMecha#52]
## Story

As a user/developer I want a single place to learn how to use our library and to discover what it can do. Minimal example game which covers essential components (keys, resources, collision).
+ mouse input (explaining how to use smalltalk api)

## Description

**Why:**  
(What value does it have? For whom?)  
value for swa students
**What:**
 - [x] collision
 - [x] resources
 - [x] keyhandling

**Comment by arthurz0** [comment]
- [ ] refactoring

- [ ] comments to explain how to use the library

**Comment by arthurz0** [comment]
bisher ca. 4h, noch nicht completed

**Comment by ben243871694** [comment]
want to stress that a minimal example game was intended, contents and game logic should not distract from it

**Comment by ekrebs5** [comment]
accepted

**Comment by arthurz0** [comment]
around 4 additional single-person hours for commenting, refactoring and loading resources
