### ISSUE TITLE
Rework Keyhandler acceptance test [1]

### ISSUE THREAD

**Issue by NiklasKoehnecke** [hpi-swa-teaching/GameMecha#54]
make the acceptance test work with any key, fix the dictionaries

**Comment by ben243871694** [comment]
two goals:
1. make sure that everything works fine with key handling (no need to look at code)
2. easy to look at code and understand what is going on

**Comment by arthurz0** [comment]
so far, 1.5 single-hours by me

**Comment by arthurz0** [comment]
45min by me

**Comment by ekrebs5** [comment]
accepted
