### ISSUE TITLE
store sound resources in methods [2]

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#55]
## Story

As an SWA student I want to store my sounds directly in the image.

## Description

**Why:**  
(What value does it have? For whom?)  
**What:**
 - [x] (Do this)

**Comment by NiklasKoehnecke** [comment]
time needed: 1

**Comment by NiklasKoehnecke** [comment]
only works for mono sounds currently

**Comment by ekrebs5** [comment]
accepted
