### ISSUE TITLE
Start investigating performance [4]

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#56]
## Story

As SWA student I want a fast game.
Eg test it with 100 colliding morphs

## Description

**Why:**  
(What value does it have? For whom?)  
**What:**
 - [x] (Do this)

**Comment by NiklasKoehnecke** [comment]
for 100 rotating objects the collision does not seem to have any impact on the fps, for 500 it has a noticeable one (5fps) but the frame rate is 13fps without it, so not very playable anyway

**Comment by ekrebs5** [comment]
accepted, for now the performance with 100 morphs should be enough for swa games
