### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#58]
Discuss the following points with @codeZeilen 

- [x] is the performance with 500  morphs important?
- [x] should the keyHandler check periodically or the morph?
- [ ] should function and/or blocks be registered on keystroke?

**Comment by ben243871694** [comment]
- [ ] what to do now as performance doesn't make sense and we don't have features which add value
- [ ] again: how much should we implement, what's up to swa students
- [ ] keyhandler periodisch?
- [ ] how to implement pixel-based collision

**Comment by Tobias314** [comment]
- [ ] ask patrick if our testing with writing files to the filesystem before reading them is ok (and can be presented in our presentation). Or should we use

**Comment by ben243871694** [comment]
- [ ] requirements: how can we measure code quality? swalint? anzahl verletzer idiome aus swa < 10? eigene coding-standards eingehalten?

**Comment by arthurz0** [comment]
possibility: make keyhandling plattform independent outside of the library
