### ISSUE TITLE
Resource Enhancement [8]

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#65]
## Story

If I have multiple games that have a "player"/"player.png" (or similiar), it should still work (files are still in different paths).

I want to reset the cache (best case for only one folder or game prefix) if I changed the pictures.

(Maybe) I want to get all pictures of one game / prefix

## Description

**Why:**  
In SWA, all games are loaded into one image
**What:**
 - [x] Prepare ResourceLoaders
 - [x] flush cache
 - [x] get all images from game
 - [ ] test with different games

**Comment by NiklasKoehnecke** [comment]
after a bit of thought this makes the handling of images and sound a lot more inconvenient for the swa students

**Comment by ben243871694** [comment]
another option: dont use global state. will measure how much time it takes to load images from disk and decide if its okay to do this every time a game starts

**Comment by ben243871694** [comment]
description of user story and requirements from eva is not up to date.
we removed the resource locator because game objects will need a reference to the game anyways (because of keyhandling), so access is easy. 
each game instantiates it's own resource managers at startup

**Comment by ekrebs5** [comment]
accepted
