### ISSUE TITLE
REFACTORING AND CLEANUP

### ISSUE THREAD

**Issue by ben243871694** [hpi-swa-teaching/GameMecha#68]
## Story

As a user/developer I want...
my team to get a good grade and therefore they need to refactor to the max

***architecture and features***
 - [x] N resource to method loading - be able to store them on instance side
 - [x] N B test & resource loading architecture
 - [x] B make sure the rest of gm-core architecture is ok
 - [x] B mock objects in tests for i/o

***refactoring***
 - [x] T go through flags
 - [x] T prefix in external methods
 - [x] B rename long classnames
 - [x] B demogame refactoring
 - [x] N unify testing style
 - [x] A parameter/variable naming conventions
 - [x] enforce styleguide - EVERYONE, check when you read code

***documentation***
 - [x] T class comments
 - [x] T acceptance tests comments

***ganz am ende***
 - [x] A swalint
 - [x] T comments in methods (not in acceptance tests, stuff which is important for swa students, about meta programming)
 - [x] A method categories (rename existing and categorize all)

**Comment by ben243871694** [comment]
estimated: 25

**Comment by NiklasKoehnecke** [comment]
class comments not done yet, unchecked again

**Comment by NiklasKoehnecke** [comment]
unified testing style, resource&test loading architecture to be reviewed
